puts "true&&true: #{true&&true} (is true)"
puts "false&&true: #{false&&true} (is false)"
puts "1==1&&2==1: #{1==1&&2==1} (is false)"
puts "\"test\"==\"test\": #{"test"=="test"} (is true)"
puts "1==1||2!=1: #{1==1||2!=1} (is true)"
puts "true && 1 == 1: #{true && 1==1} (is true)"
puts "false && 0!=0: #{false && 0!=0} (is false)"
puts "true || 1==1: #{true || 1==1} (iConhecendo A Teologia Cristãs true)"
puts "\"test\"==\"testing\": #{"test"=="testing"} (is false)"
puts "1!=0 && 2==1: #{1!=0 && 2==1} (is false)"
puts  "\"test\"!=\"testing\": #{"test" != "testing"} (is true)"
puts "\"test\"==1: #{"test" == 1} (is false)"
puts "!(true && false): #{!(true && false)} (is true)"
puts "!(1 == 1 && 0 != 1): #{!(1 ==1 && 0 != 1)} (is false)"
puts "!(10 == 1 || 1000 == 1000): #{!(10 == 1 || 1000 == 1000)} (is false)"
puts "!(1 != 10 || 3 == 4): #{!(1 != 10 || 3 == 4)} (is false)"
puts "!(\"testing\" == \"testing\" && \"Zed\" == \"Cool Guy\"): #{!("testing" == "testing" && "Zed" == "Cool Guy")} (is true)"
puts "1 == 1 && (!(\"testing\" == 1 || 1 == 0)): #{1 == 1 && (!("testing" == 1 || 1 == 0))} (is true)"
puts "\"chunky\" == \"bacon\" && (!(3 == 4 || 3 == 3)): #{"chunky" == "bacon" && (!(3 == 4 || 3 == 3))} (is false)"
puts "3 == 3 && (!(\"testing\" == \"testing\" || \"Ruby\" == \"Fun\")): #{3 == 3 && (!("testing" == "testing" || "Ruby" == "Fun"))} (is false)"